---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service2
  labels:
    name: kafka
spec:
  ports:
  - port: 9094
    name: kafka-port
    protocol: TCP
  selector:
    app: kafka
    id: "2"
  type: LoadBalancer